name: Run tests and upload coverage

on:
  push:
    branches:
        - '*'
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install npm dev dependencies
        run: npm add jest coveralls

      - name: Run tests with coverage
        run: npm run coverage